import { GoogleGenAI } from "@google/genai";

// Ensure API key is present
const apiKey = process.env.API_KEY || '';

const ai = new GoogleGenAI({ apiKey });

/**
 * Transforms an image based on a historical prompt using Gemini 2.5 Flash Image.
 */
export const generateTimeTravelPhoto = async (
  base64Image: string,
  prompt: string
): Promise<string> => {
  if (!apiKey) {
    throw new Error("API Key is missing. Please set process.env.API_KEY.");
  }

  try {
    // Remove data URL prefix if present to get clean base64
    const base64Data = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');
    
    // Model: gemini-2.5-flash-image (Nano Banana) as requested for image editing/generation
    const modelId = 'gemini-2.5-flash-image';

    const response = await ai.models.generateContent({
      model: modelId,
      contents: {
        parts: [
            {
                // We pass the prompt directly now, allowing full customization from the caller
                text: prompt
            },
            {
                inlineData: {
                    data: base64Data,
                    mimeType: 'image/jpeg' 
                }
            }
        ]
      },
      // Config specific to the prompt
      config: {
        // We can't use responseMimeType for image models usually, but we expect an image back in parts
      }
    });

    // Extract the image from the response
    if (response.candidates && response.candidates.length > 0) {
        const parts = response.candidates[0].content.parts;
        for (const part of parts) {
            if (part.inlineData && part.inlineData.data) {
                return `data:image/png;base64,${part.inlineData.data}`;
            }
        }
    }

    throw new Error("No image generated by Gemini.");

  } catch (error) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
};